### ISSUE TITLE
Certain PHP keywords not highlighted properly.

### ISSUE THREAD

**Issue by jmarkst** [massivemadness/EditorKit#4]
In PHP, certain keywords are not properly highlighted by the parser: `require`, `require_once`, and `trait`. These are some that I use frequently, but the [list at the PHP website](https://www.php.net/manual/en/reserved.keywords.php) has some relatively obscure and newer keywords which the editor may does not recognize as proper keywords (especially some built-in functions like `isset()` and `array()`).

**Comment by massivemadness** [comment]
Fixed
