### ISSUE TITLE
Please give Java code plz .......

### ISSUE THREAD

**Issue by ghost** [massivemadness/EditorKit#6]
val pluginSupplier = PluginSupplier.create {
    pinchZoom { // whether the zoom gesture enabled
        minTextSize = 10f
        maxTextSize = 20f
    }
    lineNumbers {
        lineNumbers = true // line numbers visibility
        highlightCurrentLine = true // whether the current line will be highlighted
    }
    highlightDelimiters() // highlight open/closed brackets beside the cursor
    autoIndentation {
        autoIndentLines = true // whether the auto indentation enabled
        autoCloseBrackets = true // automatically close open parenthesis/bracket/brace
        autoCloseQuotes = true // automatically close single/double quote when typing
    }
}
editor.plugins(pluginSupplier)

**Comment by ghost** [comment]
Plz reply...

**Comment by massivemadness** [comment]
Hi @SharukFT, it's recommended to use kotlin, although this code can be written in java
```java
TextProcessor textEditor = ...
        
PluginSupplier supplier = PluginSupplier.Companion.create(pluginSupplier -> {

    PinchZoomPlugin pinchZoomPlugin = new PinchZoomPlugin();
    pinchZoomPlugin.setMinTextSize(10f);
    pinchZoomPlugin.setMaxTextSize(20f);
    pluginSupplier.plugin(pinchZoomPlugin); // adding plugin to PluginSupplier

    LineNumbersPlugin lineNumbersPlugin = new LineNumbersPlugin();
    lineNumbersPlugin.setLineNumbers(true);
    lineNumbersPlugin.setHighlightCurrentLine(true);
    pluginSupplier.plugin(lineNumbersPlugin); // adding plugin to PluginSupplier
            
    // etc

    return Unit.INSTANCE;
});
textEditor.plugins(supplier);
```
